version: "2"

services:
    node:
        build:
            dockerfile: Dockerfile
            context: .
        command: bash -c "while true; do echo 'I am alive!'; sleep 3600; done"
        ports:
            - 3005:3005
        depends_on:
            - mongo
        links:
            - mongo:mongo.local
        volumes:
            - .:/webapp

    mongo:
        image: mongo
        volumes:
            - mongo-volume:/data/db

volumes:
    mongo-volume:
